apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: certificate-api-ingress
  namespace: certificate-platform
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: certificate-api
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: frontend
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 8200
        - protocol: TCP
          port: 4317
