apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: certificate-api
  namespace: certificate-platform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: certificate-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
